CAREER_SEED_DATA = [
    {
        "name": "Software Engineer",
        "avg_starting_salary": 10.0,
        "avg_salary_growth": 0.12,
        "industry_growth": 0.18,
        "stress_score": 6.5,
        "flexibility_score": 7.5,
        "remote_score": 9.0,
        "automation_risk": 0.35,
        "education_years": 4,
        "promotion_rate": 0.15,
        "layoff_risk": 0.12,
        "demand_score": 92.0,
        "description": "Design, develop, and maintain software systems across industries.",
        "recommended_skills": "AI Tools,Cloud Computing,Prompt Engineering,System Design,DevOps",
        "profile": {
            "coding": 10, "math": 8, "biology": 1, "business": 5,
            "creativity": 7, "risk": 6, "wlb": 6, "remote": 9,
            "leadership": 5, "education": 4,
        },
    },
    {
        "name": "Data Scientist",
        "avg_starting_salary": 12.0,
        "avg_salary_growth": 0.14,
        "industry_growth": 0.22,
        "stress_score": 6.0,
        "flexibility_score": 7.0,
        "remote_score": 8.5,
        "automation_risk": 0.40,
        "education_years": 5,
        "promotion_rate": 0.13,
        "layoff_risk": 0.10,
        "demand_score": 88.0,
        "description": "Extract insights from data using statistics, ML, and analytics.",
        "recommended_skills": "Machine Learning,Python,Statistics,MLOps,Data Engineering",
        "profile": {
            "coding": 9, "math": 10, "biology": 2, "business": 6,
            "creativity": 6, "risk": 5, "wlb": 6, "remote": 8,
            "leadership": 4, "education": 5,
        },
    },
    {
        "name": "AI Engineer",
        "avg_starting_salary": 15.0,
        "avg_salary_growth": 0.16,
        "industry_growth": 0.28,
        "stress_score": 7.0,
        "flexibility_score": 6.5,
        "remote_score": 8.0,
        "automation_risk": 0.30,
        "education_years": 5,
        "promotion_rate": 0.14,
        "layoff_risk": 0.11,
        "demand_score": 95.0,
        "description": "Build and deploy AI/ML systems at scale.",
        "recommended_skills": "Deep Learning,LLMs,Cloud AI,Prompt Engineering,MLOps",
        "profile": {
            "coding": 10, "math": 9, "biology": 1, "business": 5,
            "creativity": 7, "risk": 7, "wlb": 5, "remote": 8,
            "leadership": 5, "education": 5,
        },
    },
    {
        "name": "Doctor",
        "avg_starting_salary": 8.0,
        "avg_salary_growth": 0.08,
        "industry_growth": 0.10,
        "stress_score": 9.0,
        "flexibility_score": 3.0,
        "remote_score": 2.0,
        "automation_risk": 0.15,
        "education_years": 10,
        "promotion_rate": 0.08,
        "layoff_risk": 0.02,
        "demand_score": 90.0,
        "description": "Diagnose and treat patients in clinical settings.",
        "recommended_skills": "Telemedicine,Medical AI Tools,Research,Patient Communication",
        "profile": {
            "coding": 2, "math": 7, "biology": 10, "business": 3,
            "creativity": 3, "risk": 3, "wlb": 3, "remote": 2,
            "leadership": 6, "education": 10,
        },
    },
    {
        "name": "Chartered Accountant",
        "avg_starting_salary": 7.0,
        "avg_salary_growth": 0.09,
        "industry_growth": 0.08,
        "stress_score": 7.5,
        "flexibility_score": 5.0,
        "remote_score": 5.0,
        "automation_risk": 0.55,
        "education_years": 5,
        "promotion_rate": 0.10,
        "layoff_risk": 0.06,
        "demand_score": 75.0,
        "description": "Manage financial records, audits, and tax compliance.",
        "recommended_skills": "Financial Analytics,ERP Systems,Data Analysis,Compliance Tech",
        "profile": {
            "coding": 3, "math": 9, "biology": 1, "business": 9,
            "creativity": 2, "risk": 4, "wlb": 4, "remote": 5,
            "leadership": 5, "education": 5,
        },
    },
    {
        "name": "Lawyer",
        "avg_starting_salary": 6.0,
        "avg_salary_growth": 0.07,
        "industry_growth": 0.06,
        "stress_score": 8.0,
        "flexibility_score": 4.0,
        "remote_score": 4.0,
        "automation_risk": 0.45,
        "education_years": 6,
        "promotion_rate": 0.09,
        "layoff_risk": 0.05,
        "demand_score": 70.0,
        "description": "Provide legal counsel and represent clients in legal matters.",
        "recommended_skills": "Legal Tech,Contract AI,Negotiation,Digital Evidence",
        "profile": {
            "coding": 1, "math": 4, "biology": 1, "business": 8,
            "creativity": 5, "risk": 5, "wlb": 4, "remote": 4,
            "leadership": 7, "education": 6,
        },
    },
    {
        "name": "Teacher",
        "avg_starting_salary": 4.5,
        "avg_salary_growth": 0.05,
        "industry_growth": 0.07,
        "stress_score": 6.0,
        "flexibility_score": 6.0,
        "remote_score": 5.0,
        "automation_risk": 0.25,
        "education_years": 4,
        "promotion_rate": 0.06,
        "layoff_risk": 0.03,
        "demand_score": 80.0,
        "description": "Educate and mentor students across academic levels.",
        "recommended_skills": "EdTech,Online Teaching,Digital Content,Student Analytics",
        "profile": {
            "coding": 2, "math": 5, "biology": 5, "business": 3,
            "creativity": 8, "risk": 2, "wlb": 7, "remote": 5,
            "leadership": 6, "education": 4,
        },
    },
    {
        "name": "Product Manager",
        "avg_starting_salary": 14.0,
        "avg_salary_growth": 0.13,
        "industry_growth": 0.15,
        "stress_score": 7.5,
        "flexibility_score": 7.0,
        "remote_score": 7.5,
        "automation_risk": 0.30,
        "education_years": 4,
        "promotion_rate": 0.12,
        "layoff_risk": 0.10,
        "demand_score": 85.0,
        "description": "Define product strategy and coordinate cross-functional teams.",
        "recommended_skills": "AI Product Strategy,Data Analytics,UX Research,Agile Leadership",
        "profile": {
            "coding": 5, "math": 6, "biology": 1, "business": 9,
            "creativity": 8, "risk": 7, "wlb": 5, "remote": 7,
            "leadership": 9, "education": 4,
        },
    },
    {
        "name": "UX Designer",
        "avg_starting_salary": 8.0,
        "avg_salary_growth": 0.11,
        "industry_growth": 0.14,
        "stress_score": 5.5,
        "flexibility_score": 8.0,
        "remote_score": 8.5,
        "automation_risk": 0.35,
        "education_years": 4,
        "promotion_rate": 0.11,
        "layoff_risk": 0.08,
        "demand_score": 82.0,
        "description": "Design intuitive user experiences for digital products.",
        "recommended_skills": "AI-Assisted Design,Figma,User Research,Design Systems",
        "profile": {
            "coding": 4, "math": 3, "biology": 1, "business": 5,
            "creativity": 10, "risk": 5, "wlb": 7, "remote": 8,
            "leadership": 4, "education": 4,
        },
    },
    {
        "name": "Cybersecurity Engineer",
        "avg_starting_salary": 11.0,
        "avg_salary_growth": 0.13,
        "industry_growth": 0.20,
        "stress_score": 7.0,
        "flexibility_score": 6.0,
        "remote_score": 7.0,
        "automation_risk": 0.20,
        "education_years": 4,
        "promotion_rate": 0.12,
        "layoff_risk": 0.07,
        "demand_score": 93.0,
        "description": "Protect systems and networks from cyber threats.",
        "recommended_skills": "Cloud Security,AI Threat Detection,Penetration Testing,Zero Trust",
        "profile": {
            "coding": 8, "math": 7, "biology": 1, "business": 4,
            "creativity": 5, "risk": 6, "wlb": 5, "remote": 7,
            "leadership": 5, "education": 4,
        },
    },
    {
        "name": "Entrepreneur",
        "avg_starting_salary": 5.0,
        "avg_salary_growth": 0.20,
        "industry_growth": 0.12,
        "stress_score": 9.5,
        "flexibility_score": 9.0,
        "remote_score": 8.0,
        "automation_risk": 0.25,
        "education_years": 3,
        "promotion_rate": 0.05,
        "layoff_risk": 0.35,
        "demand_score": 60.0,
        "description": "Build and scale businesses from the ground up.",
        "recommended_skills": "Fundraising,Digital Marketing,AI Automation,Financial Modeling",
        "profile": {
            "coding": 5, "math": 6, "biology": 2, "business": 10,
            "creativity": 9, "risk": 10, "wlb": 3, "remote": 8,
            "leadership": 10, "education": 3,
        },
    },
]


def seed_database(db):
    from app.models.career import Career

    if db.query(Career).count() > 0:
        return

    for data in CAREER_SEED_DATA:
        career = Career(
            name=data["name"],
            avg_starting_salary=data["avg_starting_salary"],
            avg_salary_growth=data["avg_salary_growth"],
            industry_growth=data["industry_growth"],
            stress_score=data["stress_score"],
            flexibility_score=data["flexibility_score"],
            remote_score=data["remote_score"],
            automation_risk=data["automation_risk"],
            education_years=data["education_years"],
            promotion_rate=data["promotion_rate"],
            layoff_risk=data["layoff_risk"],
            demand_score=data["demand_score"],
            description=data["description"],
            recommended_skills=data["recommended_skills"],
        )
        db.add(career)

    db.commit()
